### ISSUE TITLE
CFBundleVersion missing when building for iOS

### ISSUE THREAD

**Issue by dvshelley** [3a4oT/DateToolsObjC#13]
When I build the framework for iOS, the CFBundleVersion entry is left out of the Info.plist. This causes its app to get rejected by Apple's automatic .ipa validation.

This was introduced in commit (- Added Swift Package Manager support., 349a899c2e2be0d01625fa363d1b9a658b43bc03) when building for iOS. The previous 1.0.3 release doesn't have this problem.

Test:
- checkout master/1.0.4
- open the project
- select an iOS target
- build
- right click on DateToolsObjC.framework in the file navigator in Xcode and select Show In Finder
- Open the folder and then look at the Info.plist file

Expected:
- With the 1.0.3 release there was an entry for CFBundleVersion that was set to 1.0.0
Actual:
- No entry for CFBundleVersion

Unfortunately I can't quite figure out what in the commit caused this specifically?

See also: https://github.com/3a4oT/DateToolsObjC/issues/4

**Comment by 3a4oT** [comment]
thanks for reporting. Should be fixed in #14 . I added unit test for this case. Will update 1.0.4 tag.

**Comment by dvshelley** [comment]
Much better. Thanks!
