### ISSUE TITLE
Error from iTunesConnect. 

### ISSUE THREAD

**Issue by bwhiteley** [3a4oT/DateToolsObjC#4]
When submitting an app with this framework (built with Carthage), iTunesConnect reports this error: 
"This bundle .../Frameworks/DateToolsObjC.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion."

**Comment by bwhiteley** [comment]
Actually, the framework in question is the pre-built framework in the .zip from the 1.0.0 release.

**Comment by 3a4oT** [comment]
Hey, @bwhiteley I have faced with the same issue but was under impression that I have fixed it since various apps which using this framework are in the app store. You can try for now
```carthage bootstrap DateToolsObjC --platform iOS --no-use-binaries``` to build by yourself. I have created *1.0.1 release* which also have zipped framework so you can try it as well.

**Comment by 3a4oT** [comment]
@bwhiteley Does it help?

**Comment by bwhiteley** [comment]
It works. Thanks!
